apiVersion: apps/v1 
kind: Deployment
metadata:
  name: commands-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandsservice
  template:
    metadata:
      labels:
        app: commandsservice
    spec:
      containers:
      - name: commandsservice
        image: alikorkmaz03/commandsservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-serv
spec:  
    type: ClusterIP
    selector:
      app: commandsservice
    ports:
     - name: commandsservice
       protocol: TCP
       port: 80
       targetPort: 80   

        
#help codes
# kubectl apply -f commands-depl.yaml-> for deploy apply kubernetes

#kubectl get deployments

#kubectl get pods