apiVersion: apps/v1 
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: alikorkmaz03/platformservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
    
#help codes
# kubectl apply -f platforms-depl.yaml-> for deploy apply kubernetes

#kubectl get deployments

#kubectl get pods